<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Settings\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventAssos.Core\EventAssos.Core.csproj" />
    <ProjectReference Include="..\EventAssos.Domain\EventAssos.Domain.csproj" />
  </ItemGroup>

</Project>
